//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
// 
namespace WSClient.localhost1 {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SampleSoap", Namespace="http://tempuri.org/DISSample/Sample")]
    public class Sample : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Sample() {
            this.Url = "http://localhost/DISSample/Sample.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DISSample/Sample/Login", RequestNamespace="http://tempuri.org/DISSample/Sample", ResponseNamespace="http://tempuri.org/DISSample/Sample", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Login(string DataBaseServer, string DataBaseName, string DataBaseType, string DataBaseUserName, string DataBasePassword, string CompanyUserName, string CompanyPassword, string Language, string LicenseServer, string sPort) {
            object[] results = this.Invoke("Login", new object[] {
                        DataBaseServer,
                        DataBaseName,
                        DataBaseType,
                        DataBaseUserName,
                        DataBasePassword,
                        CompanyUserName,
                        CompanyPassword,
                        Language,
                        LicenseServer,
                        sPort});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLogin(string DataBaseServer, string DataBaseName, string DataBaseType, string DataBaseUserName, string DataBasePassword, string CompanyUserName, string CompanyPassword, string Language, string LicenseServer, string sPort, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Login", new object[] {
                        DataBaseServer,
                        DataBaseName,
                        DataBaseType,
                        DataBaseUserName,
                        DataBasePassword,
                        CompanyUserName,
                        CompanyPassword,
                        Language,
                        LicenseServer,
                        sPort}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndLogin(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DISSample/Sample/GetBPList", RequestNamespace="http://tempuri.org/DISSample/Sample", ResponseNamespace="http://tempuri.org/DISSample/Sample", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetBPList(string SessionID, string CardType) {
            object[] results = this.Invoke("GetBPList", new object[] {
                        SessionID,
                        CardType});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetBPList(string SessionID, string CardType, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetBPList", new object[] {
                        SessionID,
                        CardType}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlNode EndGetBPList(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DISSample/Sample/AddBP", RequestNamespace="http://tempuri.org/DISSample/Sample", ResponseNamespace="http://tempuri.org/DISSample/Sample", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode AddBP(string SessionID, string xmlBPObject) {
            object[] results = this.Invoke("AddBP", new object[] {
                        SessionID,
                        xmlBPObject});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAddBP(string SessionID, string xmlBPObject, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AddBP", new object[] {
                        SessionID,
                        xmlBPObject}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlNode EndAddBP(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DISSample/Sample/GetEmptyBPXml", RequestNamespace="http://tempuri.org/DISSample/Sample", ResponseNamespace="http://tempuri.org/DISSample/Sample", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetEmptyBPXml(string SessionID) {
            object[] results = this.Invoke("GetEmptyBPXml", new object[] {
                        SessionID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetEmptyBPXml(string SessionID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetEmptyBPXml", new object[] {
                        SessionID}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlNode EndGetEmptyBPXml(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }
    }
}
