#ifndef _APPOBJECTS_H_
	#define _APPOBJECTS_H_

/*************************************************************/
/* Object Type Constants (Entries to the Objects Functions Grid) */
//Tmp table Objects
#define     CRTOBJS  -2000L //Defined for all temp object which used in ExQryCriteria, all temp object should be < -2000, like -2001 etc,on.
#define     PLNTMP   -2001L //PLN TEMP LIST
#define     UGPTMP   -2002L //UGP TEMP LIST
#define     UOMTMP   -2003L //UOM TEMP LIST

/*************************************************************/
// Defines for Business Objects are generated by XmlCompiler:
#include "BusinessObjects.h"
// Not defined in BusinessObjects.h:
#define		TXT		-18L			// TXT auxiliary Object used as identifier in Production Order and BOM Lines
#define		CRD1X   -17L			// CRD1 auxiliary Object
#define		BASE    -15L			// User to store base object DAGs in document generator
#define		EWAX    -13L			// Early Watch Alert Service - Extended
#define		BTX	    -8L				// Batch auxiliary Object
#define		SRX	    -7L				// Serial auxiliary Object
#define		TMP	    -2L				// Temporary Object
#define		ENT     88L				// Panama - enterada
#define		SAL     89L				// Panama - salida
#define		TRA     90L				// Panama - traspaso
#define		CUMI    154L			// User Menu
#define		RTC     1470000096L		// Fixed Assets Retirement Credit Memo
#define		CASE1   200000000L		// Internal Reconciliation Upgrade 2007A (CASE1 is used instead of CASE because "case" is a reserved word)
/*************************************************************/
#define		WIDGET_TYPE		WDT	// Widget Type

/***************************************/
#define		NO_LIMIT			0x00
#define		CREDIT_LIMIT		0x01
#define		OBLIGO_LIMIT		0x02
#define		ADD_DLN_BALANCE		0x40
/***************************************/
#define		ORDERS_LIMIT		0x01
#define		DELIVERY_LIMIT		0x02
#define		SALES_LIMIT			0x40
#define     PICKLIST_LIMIT		0x80
/****************************		Extended Commands		*********************************/
#define		ooExAutoMode			0x00000001
#define		ooExJoinReport			0x00000002
#define		ooExExpandTransLine		0x00000004
#define		ooExAddToMsgForm		0x00000008
#define		ooExRoundLinesToSum		0x00000010
#define		ooExAddBatchNoClose		0x00000020
#define		ooExAddBatchClose		0x00000040
#define		ooExCloseBatch			0x00000080
#define		ooDontStartSqlTrans		0x00000100 //Deprecated, it's replaced with the TransScope mechanism.
#define		ooCreateTransOnly		0x00000200
#define		ooDontAdvanceAutoKey	0x00000400
#define		ooDontAdvanceNextNum	0x00000800
#define		ooDontCheckTranses		0x00001000
#define		ooDontSetMainFile		0x00002000
#define		ooDontUpdateArrFile		0x00004000
#define		ooDontGetArrayFile		0x00008000

#define		ooDontValidateData1		0x00010000
#define		ooDontValidateData2		0x00020000
#define		ooExInternalAutoMode	0x00040000
#define		ooExDontUpdateBalance	0x00080000

#define		ooExAttachReport		0x00100000
#define		ooExBSPCreateJE			0x00200000
#define		ooExUseFillProc			0x00400000

#define		ooDontUpdateBudget		0x00800000
#define		ooImportData			0x01000000

#define		ooDraftDocument			0x02000000
#define		ooDontWriteTrans		0x04000000
#define		ooDeleteOld				0x08000000

#define		ooDontCreateFIX1		0x10000000
#define		ooJECancelByFIX         0x20000000
#define		ooJECreatedByPEC		0x40000000
#define		ooTransferAssetClass	0x80000000

//*** i040882: 
//Please don't use following four flags. Their usage makes the code really 
//confusing. Instead, create a uniquely named flag ooEx2... I know 
//there might not be enough room for more flags in the bit fields. That
//is why I recommend changing the m_exCommand to a Set of integers in the 
//future.
//***
#define		ooExTempData1			0x10000000
#define		ooExTempData2			0x20000000
#define		ooExTempData3			0x40000000
#define		ooExTempData4			0x80000000

//distinguishes if BO is DPM Invoice (set) or DPM Request (not set)
//formerly ooExTempData3 was used - very confusing
#define		ooExIsJdtDpm			ooExTempData3	

//distinguishes if Invoice BO is of special type - payment invoice
//formerly ooExTempData2 was used - very confusing
#define		ooExIsPaymentInvoice	ooExTempData2	

#define     ooExInvokedByCppUnit    ooExTempData4

// Extended Commands 2
#define		ooEx2Write					0x00000001
#define		ooFromServiceCall			0x00000002
#define		ooCallSysBizObjProc			0x00000004
#define		ooDontShowFolioPrint		0x00000008
#define		ooFolioConfirmation			0x00000010
#define		ooFolioAssignment			0x00000020
#define		ooBeforeDocAdded			0x00000040
#define		ooEx2LandedCost				0x00000080
#define		ooEx2PrintToScreen			0x00000100
#define		ooEx2PrintToFile			0x00000200
#define		ooEx2PrintToImage			0x00000400
#define		ooEx2PrintToXml				0x00000800
#define		ooEx2Print					0x00001000
#define		ooFromPickNPack				0x00002000
#define		ooDontAddRecJDT				0x00004000
#define		ooExt2ReconcilAdjustment	0x00008000
#define		ooEx2IgnoreRptCopies		0x00010000
#define		ooEx2IgnoreRptPrinter		0x00020000
#define		ooExTreatAsUpgrade			0x00040000
#define		ooDisableRptInactiveMDFilter	0x00080000
#define		ooIntlReconcilAdjustment	0x00100000
#define		ooEx2SetCurrentRefDate		0x00200000
#define		ooDontUpdateInventory		0x00400000
#define		ooDontValidateItem			0x00800000
#define		ooEx2PrintToPdf				0x01000000
#define		ooEx2TreatAsDeleteInsert	0x02000000
#define		ooEx2PrintToEmail			0x04000000
#define		ooDontCloseFocus			0x08000000
#define		ooEx2TempData1				0x10000000	// ooExTempData1 is already being used with SetExCommand2/GetExCommand2
#define		ooEx2JdtFillFrgnCurr		0x20000000	// means that FC symbol will be written to JDT1 line also for zero amount
// VF_AmountDifferences
#define		ooEx2IgnoreVatAccount		0x40000000	// ignore Vat account definition for vat group
#define		ooEx2TempData4				0x80000000	// ooExTempData4 is already being used with SetExCommand2/GetExCommand2

// Extended Commands 3
#define		ooEx3DontTouchNextNum		0x00000001
#define		ooEx3ArchiveStockCompress	0x00000002
#define		ooEx3ForceDeleteInsertForZeroRecs 0x00000004 // force delete/insert for update scenario in order to allow deletion of all records
#define		ooEx3GloballyUpdatePrice	0x00000008
#define		ooEnableInactiveBP			0x00000010
#define     ooSuppressCopyFromGrid      0x00000020
#define     ooEx3ExportToAttachmentsFolder 0x00000040
#define     ooEx3AttachPDFToDoc           0x00000080
#define		ooEx3ExportToFile			0x00000100
// End Extended Commands 3

// DT(Data Transfer) Extended Commands
#define		ooDataFromDT			0x00000001
#define		ooDoAsUpgrade			0x00000002
#define		ooDoNotCheckDates		0x00000004
#define		ooOBServerDT			0x00000008
#define		ooOBServerUpdate		0x00000010
#define		ooUpdatePriceOnly		0x00000020
#define		ooUpdateBOMPriceOnly	0x00000040
#define		ooChangeAsmBoMWhs		0x00000080		// VF_EnableChangeAsmBoMWhs
#define		ooOBServerAdd			0x00000100
#define		ooOBServerRemove		0x00000200
#define		ooOBServerGetByParam	0x00000400
#define		ooOBServerClose			0x00000800
#define		ooOBServerCancel		0x00001000
#define		ooOBServerGetList		0x00002000
#define     ooOBServerReopen		0x00004000
#define		ooUseRptInactiveMDFilter		0x00008000
#define		ooUseDocInactiveMDFilter		0x00010000
#define		ooBSPExchangeRateDiff			0x00020000
#define		ooDocInactiveFilterByCheckbox	0x00040000
#define		ooAssetItemMasterDataFlag		0x00080000
#define		ooExt3SkipINVSetTotals			0x00100000

/***************************	Warning	Level	********************************/
#define		OOWL_AS_ERROR			1
#define		OOWL_PROMPT_USER		2
#define		OOWL_DISCARD			3

#define		OO_TRANS_RETRIES		6
#define		OO_TRANS_RETRY_TIMEOUT	2		// In Seconds

#endif
