'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
'
Namespace localhost
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SampleSoap", [Namespace]:="http://tempuri.org/DISSample/Sample")>  _
    Public Class Sample
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/DISSample/Sample.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DISSample/Sample/Login", RequestNamespace:="http://tempuri.org/DISSample/Sample", ResponseNamespace:="http://tempuri.org/DISSample/Sample", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Login(ByVal DataBaseServer As String, ByVal DataBaseName As String, ByVal DataBaseType As String, ByVal DataBaseUserName As String, ByVal DataBasePassword As String, ByVal CompanyUserName As String, ByVal CompanyPassword As String, ByVal Language As String, ByVal LicenseServer As String, ByVal sPort As String) As String
            Dim results() As Object = Me.Invoke("Login", New Object() {DataBaseServer, DataBaseName, DataBaseType, DataBaseUserName, DataBasePassword, CompanyUserName, CompanyPassword, Language, LicenseServer, sPort})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginLogin(ByVal DataBaseServer As String, ByVal DataBaseName As String, ByVal DataBaseType As String, ByVal DataBaseUserName As String, ByVal DataBasePassword As String, ByVal CompanyUserName As String, ByVal CompanyPassword As String, ByVal Language As String, ByVal LicenseServer As String, ByVal sPort As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Login", New Object() {DataBaseServer, DataBaseName, DataBaseType, DataBaseUserName, DataBasePassword, CompanyUserName, CompanyPassword, Language, LicenseServer, sPort}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndLogin(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DISSample/Sample/GetBPList", RequestNamespace:="http://tempuri.org/DISSample/Sample", ResponseNamespace:="http://tempuri.org/DISSample/Sample", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetBPList(ByVal SessionID As String, ByVal CardType As String) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("GetBPList", New Object() {SessionID, CardType})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        Public Function BeginGetBPList(ByVal SessionID As String, ByVal CardType As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetBPList", New Object() {SessionID, CardType}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetBPList(ByVal asyncResult As System.IAsyncResult) As System.Xml.XmlNode
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DISSample/Sample/AddBP", RequestNamespace:="http://tempuri.org/DISSample/Sample", ResponseNamespace:="http://tempuri.org/DISSample/Sample", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AddBP(ByVal SessionID As String, ByVal xmlBPObject As String) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("AddBP", New Object() {SessionID, xmlBPObject})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        Public Function BeginAddBP(ByVal SessionID As String, ByVal xmlBPObject As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AddBP", New Object() {SessionID, xmlBPObject}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAddBP(ByVal asyncResult As System.IAsyncResult) As System.Xml.XmlNode
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DISSample/Sample/GetEmptyBPXml", RequestNamespace:="http://tempuri.org/DISSample/Sample", ResponseNamespace:="http://tempuri.org/DISSample/Sample", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetEmptyBPXml(ByVal SessionID As String) As System.Xml.XmlNode
            Dim results() As Object = Me.Invoke("GetEmptyBPXml", New Object() {SessionID})
            Return CType(results(0),System.Xml.XmlNode)
        End Function
        
        '<remarks/>
        Public Function BeginGetEmptyBPXml(ByVal SessionID As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetEmptyBPXml", New Object() {SessionID}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetEmptyBPXml(ByVal asyncResult As System.IAsyncResult) As System.Xml.XmlNode
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Xml.XmlNode)
        End Function
    End Class
End Namespace
